/**
 * OAuth contract inputs shared by the real Worker and the OpenAI descriptor
 * freeze gate. Values in this module are public protocol metadata, not secrets.
 */

export const OPENAI_REVIEW_ORIGIN = "https://openai-mcp.frihet.io";

interface FrozenOAuthProviderOptions {
  apiRoute: string;
  authorizeEndpoint: string;
  tokenEndpoint: string;
  clientRegistrationEndpoint: string;
  scopesSupported: string[];
  accessTokenTTL: number;
  refreshTokenTTL: number;
  allowPlainPKCE: boolean;
}

/**
 * Byte-compatible extraction of the options previously inlined in the Worker.
 * index.ts spreads this object into the real OAuthProvider constructor.
 */
export const OAUTH_PROVIDER_REVIEW_OPTIONS = {
  apiRoute: "/mcp",
  authorizeEndpoint: "/authorize",
  tokenEndpoint: "/token",
  clientRegistrationEndpoint: "/register",
  scopesSupported: ["read", "write"],
  accessTokenTTL: 3600,
  refreshTokenTTL: 2592000,
  allowPlainPKCE: false,
} satisfies FrozenOAuthProviderOptions;

function endpoint(origin: string, path: string): string {
  return new URL(path, new URL(origin).origin).toString();
}

/**
 * Materialize the public metadata generated by workers-oauth-provider 0.3.0
 * from the same options used by the Worker. The dependency version is pinned
 * separately in the canonical descriptor snapshot.
 */
export function buildOpenAIReviewOAuthContract(origin = OPENAI_REVIEW_ORIGIN) {
  const normalizedOrigin = new URL(origin).origin;
  const authorizationEndpoint = endpoint(
    normalizedOrigin,
    OAUTH_PROVIDER_REVIEW_OPTIONS.authorizeEndpoint,
  );
  const tokenEndpoint = endpoint(
    normalizedOrigin,
    OAUTH_PROVIDER_REVIEW_OPTIONS.tokenEndpoint,
  );
  const registrationEndpoint = endpoint(
    normalizedOrigin,
    OAUTH_PROVIDER_REVIEW_OPTIONS.clientRegistrationEndpoint,
  );
  const resourceMetadataUrl = endpoint(
    normalizedOrigin,
    "/.well-known/oauth-protected-resource",
  );

  return {
    authorizationServer: {
      issuer: normalizedOrigin,
      authorization_endpoint: authorizationEndpoint,
      token_endpoint: tokenEndpoint,
      registration_endpoint: registrationEndpoint,
      scopes_supported: [...OAUTH_PROVIDER_REVIEW_OPTIONS.scopesSupported],
      response_types_supported: ["code"],
      response_modes_supported: ["query"],
      grant_types_supported: ["authorization_code", "refresh_token"],
      token_endpoint_auth_methods_supported: [
        "client_secret_basic",
        "client_secret_post",
        "none",
      ],
      revocation_endpoint: tokenEndpoint,
      code_challenge_methods_supported: ["S256"],
      client_id_metadata_document_supported: false,
    },
    protectedResource: {
      resource: normalizedOrigin,
      authorization_servers: [normalizedOrigin],
      scopes_supported: [...OAUTH_PROVIDER_REVIEW_OPTIONS.scopesSupported],
      bearer_methods_supported: ["header"],
    },
    wwwAuthenticate: {
      resourceMetadataUrl,
      missingTokenHeader:
        `Bearer realm="OAuth", resource_metadata="${resourceMetadataUrl}", ` +
        'error="invalid_token", error_description="Missing or invalid access token"',
    },
  };
}
